name: Himal Sherchan
description: Blogging about programming, music, food, etc.
meta_description: "Your New Jekyll Site, Blogging about stuffs"

aboutPage: true

markdown: kramdown
highlighter: rouge

paginate: 20
baseurl: /
domain_name: 'hshercha.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'hshercha.github.io'
author:         'Himal Sherchan'

permalink:       /:year/:title/
gems: [jekyll-paginate]
defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
